### ISSUE TITLE
double faces

### ISSUE THREAD

**Issue by nan2088** [infinivision/edge-tracker#1]
Hi guys,
thanks for sharing this project.

it is interesting that you treat two faces same one if center point of one box is inside the other, and I think it might be a quite bright and economic way to tracking new detected  faces, especially for fixed camera.

The difficult part is that, how to handle situations where two detected face  contained each other's center point, or tracked faces before detecting  contained each other's center point. Do you have any ideas?

ps. a suggestion: a simplified Onet is optional after the tracking step, if capacity is enough
[https://github.com/blankWorld/MTCNN-Accelerate-Onet](url)

**Comment by loadwiki** [comment]
mtccn detector will do non-maximum suppression (NMS). NMS  is a normal step in image detector which will make sure that every cadidate ROI shares little common  area. Tracked faces should be deduplicated when center point is inside the other. This may be a problem.

**Comment by nan2088** [comment]
HI, @loadwiki 
Glead to hear from you. and thanks for your reply. In fact, I found NMS is not enough and the threshold of  iou is just too big to handle our problem. This is just my persional experience.

**Comment by loadwiki** [comment]
Maybe you can try a new DL-based face detector with higher performance, such as [ssh detector implementation by mxnet ](https://github.com/deepinsight/mxnet-SSH). You can use ssh-detector for runtime detect task for some high definition(2 million resolution) video stream with multi cpu core.
